version: '3'
services:
  proxy:
    image: nginx:latest  
    container_name: proxy 
    ports: 
      - "8000:80"          
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf 
    restart: "unless-stopped"
  express:
    build:
      context: ./source
    container_name: express
    volumes:
      - ./source:/source
      - /source/node_modules 
    restart: "unless-stopped"
  mongo:
    image: mongo:latest
    container_name: mongo
    expose:
      - "27017" 
